backend:
  name: git-gateway
  branch: main # Branch que vai mexer no repositório

publish_mode: editorial_workflow # Para fazer um esquema de revisão de novas edições
media_folder: "public/uploads" # Onde os arquivos de mídia serão armazenados
public_folder: "/uploads" # Onde a parte de mídia vai poder ser acessada
display_url: https://faiscadesignjr.com.br/ # URL que será mostrado no UI do Netlify

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

search: false
locale: 'pt'

collections:
  - name: "navbar"
    extension: "json"
    description: "Navbar com nome de todas as abas do site"
    label: "Navbar"
    folder: "content/navbar"
    slug: "navbarConfig"
    create: false
    identifier_field: "display_name"
    editor:
      preview: false
    fields:
      - {label: "Nome Painel", name: "display_name", widget: "string", hint: "Nome que aparecerá no painel administrativo"}
      - {label: "Opção 1", name: "optionOne", widget: "string", default: "início"}
      - {label: "Opção 2", name: "optionTwo", widget: "string", default: "sobre nós"}
      - {label: "Opção 3", name: "optionThree", widget: "string", default: "portfólio"}
      - {label: "Opção 4", name: "optionFour", widget: "string", default: "contato"}

  - name: "home"
    extension: "json"
    description: "Configurações da página principal"
    label: "Home"
    folder: "content/homePage"
    slug: "homePage"
    create: false
    identifier_field: "display_name"
    editor:
      preview: false
    fields:
      - {label: "Nome Painel", name: "display_name", widget: "string", hint: "Nome que aparecerá no painel administrativo"}
      # BANNER
      - label: "Banner Principal"
        name: "banner"
        widget: "object"
        fields:
          - {label: "Descrição do Propósito", name: "purpose", widget: "string", default: "PROPORCIONAMOS SOLUÇÕES CRIATIVAS PARA PROJETOS EXCLUSIVOS"}
          - {label: "Logo Banner", name: "logo", widget: "image"}
          - {label: "Título", name: "tittle", widget: "string", default: "SOMOS A FAÍSCA!"}
          - {label: "Descrição da Empresa", name: "companyDesc", widget: "string", default: "UMA EMPRESA JÚNIOR DE DESIGN VISUAL E DE PRODUTO DA UFRGS"}

      # LEARN MORE
      - label: "Seção Learn More"
        name: "learnMore"
        widget: "object"
        fields:
          - {label: "O que fazemos", name: "desc", widget: "string", default: "nós fazemos design de um jeito que você nunca viu"}
          - {label: "Frase do Botão", name: "buttonPhrase", widget: "string", default: "Vem impulsionar sua marca"}
          - {label: "Rota do Botão", name: "buttonRoute", widget: "string", default: "/contato"}

      # NOSSOS SERVIÇOS
      - label: "Seção Serviços"
        name: "services"
        widget: "object"
        fields:
          - {label: "Título da Seção", name: "titleAllServices", widget: "string", default: "NOSSOS SERVIÇOS"}

      # CASES
      - label: "Seção Cases"
        name: "cases"
        widget: "object"
        fields:
          - {label: "Frase Cases", name: "phraseCases", widget: "string", default: "encontramos soluções ideais para cada tipo de desafio"}
          - {label: "Título Esquerda", name: "leftTitle", widget: "string", default: "CASES"}
          - {label: "Título Direita", name: "rightTitle", widget: "string", default: "SELECIONADOS"}
          - {label: "Texto Botão", name: "buttonPhrase", widget: "string", default: "Mais Projetos"}
          - {label: "Rota Botão", name: "buttonRoute", widget: "string", default: "/portfolio"}

      # DEPOIMENTOS
      - label: "Seção Depoimentos"
        name: "reviews"
        widget: "object"
        fields:
          - {label: "Título Depoimentos", name: "titleReviews", widget: "string", default: "O QUE NOSSOS CLIENTES TEM A DIZER"}

  - name: "servicos"
    label: "Serviços (Home)"
    description: "Lista de serviços oferecidos"
    folder: "content/servicos"
    create: true
    extension: "json"
    identifier_field: "titulo"
    sortable: true 
    editor:
      preview: false
    fields:
      - {label: "Ordem", name: "ordem", widget: "number", value_type: "int", min: 1}
      - {label: "Título do Serviço", name: "titulo", widget: "string"}
      - {label: "Descrição", name: "descricao", widget: "text"}
  
  - name: "cases"
    label: "Cases (Home)"
    description: "Portfolio de projetos"
    folder: "content/cases"
    create: true
    extension: "json"
    identifier_field: "nomeProjeto"
    editor:
      preview: false
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Nome do Projeto", name: "nomeProjeto", widget: "string"}
      - {label: "Imagem", name: "imagem", widget: "image"}
      - {label: "Link do Projeto", name: "projectLink", widget: "string"}

  - name: "depoimentos"
    label: "Reviews (Home)"
    description: "Reviews dos clientes"
    folder: "content/reviews"
    create: true
    extension: "json"
    identifier_field: "cliente"
    editor:
      preview: false
    fields:
      - {label: "Depoimento", name: "texto", widget: "text"}
      - {label: "Cliente", name: "cliente", widget: "string"}

  - name: "sobreNos"
    extension: "json"
    description: "Configurações estáticas da página Sobre Nós"
    identifier_field: "display_name"
    label: "Sobre Nós"
    folder: "content/sobreNos"
    slug: "sobreNosPage"
    create: false
    editor:
      preview: false
    fields:
      - {label: "Nome Painel", name: "display_name", widget: "string", hint: "Nome que aparecerá no painel administrativo"}
      # PROPÓSITO
      - {label: "Propósito", name: "purpose", widget: "text"}

      # SOBRE A FAÍSCA
      - label: "Sobre a Faísca"
        name: "aboutFaisca"
        widget: "object"
        fields:
          - {label: "Primeiro Parágrafo", name: "firstText", widget: "text"}
          - {label: "Segundo Parágrafo", name: "secondText", widget: "text"}
          - {label: "Logo", name: "logo", widget: "image"}

      # ÁREA DE MEMBROS
      - label: "Área de Membros"
        name: "membersArea"
        widget: "object"
        fields:
          - {label: "Título", name: "tittle", widget: "string"}
          - {label: "Subtítulo", name: "subTittle", widget: "string", required: false}

      # ESTRUTURA
      - label: "Estrutura"
        name: "structure"
        widget: "object"
        fields:
          - {label: "Título", name: "tittle", widget: "string"}
          - {label: "Texto", name: "phrase", widget: "text"}
          
          - label: "card 1"
            name: "sectionOne"
            widget: "object"
            fields:
              - {label: "Imagem", name: "img", widget: "image"}
              - {label: "Título", name: "subTittle", widget: "string"}
              - {label: "Texto", name: "text", widget: "text"}

          - label: "card 2"
            name: "sectionTwo"
            widget: "object"
            fields:
              - {label: "Imagem", name: "img", widget: "image"}
              - {label: "Título", name: "subTittle", widget: "string"}
              - {label: "Subtítulo", name: "subSubTittle", widget: "string", required: false}
              - {label: "Texto", name: "text", widget: "text"}

          - label: "card 3"
            name: "sectionThree"
            widget: "object"
            fields:
              - {label: "Imagem", name: "img", widget: "image"}
              - {label: "Título", name: "subTittle", widget: "string"}
              - {label: "Texto", name: "text", widget: "text"}

          - label: "card 4"
            name: "sectionFour"
            widget: "object"
            fields:
              - {label: "Imagem", name: "img", widget: "image"}
              - {label: "Título", name: "subTittle", widget: "string"}
              - {label: "Subtítulo", name: "subSubTittle", widget: "string", required: false}
              - {label: "Texto", name: "text", widget: "text"}

      # MEJ
      - label: "MEJ"
        name: "mej"
        widget: "object"
        fields:
          - {label: "Título", name: "tittle", widget: "string"}
          - {label: "Frase", name: "phrase", widget: "text"}
          - {label: "Imagem Principal", name: "mainImg", widget: "image"}
          - {label: "Logo Brasil Jr", name: "brasilJrImg", widget: "image"}
          - {label: "Logo Nej", name: "NejImg", widget: "image"}
          - {label: "Logo Fejers", name: "fejersImg", widget: "image"}
          - {label: "Logo Design UFRGS", name: "designUFRGSImg", widget: "image"}

  - name: "membros"
    label: "Membros (Sobre Nós)"
    folder: "content/membros"
    create: true
    extension: "json"
    identifier_field: "display_name"
    editor:
      preview: false
    fields:
      - {label: "Nome para Exibição", name: "display_name", widget: "string", hint: "Nome que aparecerá no painel administrativo"}
      - {label: "ID (único)", name: "id", widget: "string", hint: "Identificador único do cargo (ex: presidente, marketing)"}
      - label: "Membro(s) do Cargo"
        name: "members"
        widget: "list"
        fields:
          - {label: "Nome", name: "nome", widget: "string"}
          - {label: "Cargo/Ciclo", name: "ciclo", widget: "string"}
          - {label: "Foto", name: "imagem", widget: "image"}

  - name: "banners"
    label: "Portfólio"
    description: "Banners exibidos na página portfólio"
    folder: "content/banners"
    create: true
    extension: "json"
    identifier_field: "titulo"
    sortable: true
    editor:
      preview: false
    fields:
      - {label: "Ordem", name: "ordem", widget: "number", value_type: "int", min: 1}
      - {label: "Título do Projeto", name: "titulo", widget: "string"}
      - {label: "Descrição", name: "desc", widget: "string"}
      - {label: "Imagem do Projeto", name: "image", widget: "image"}
      - {label: "Rota do Projeto", name: "path", widget: "string", pattern: ['^/portfolio/[a-zA-Z0-9-]+$', "Deve começar com /portfolio/"]}
      - {label: "Mensagem de Erro", name: "erro", widget: "string", default: "Imagem não encontrada"}

  - name: "projetos"
    extension: "json"
    description: "Coleção que vai conter as paginas de projetos individuais."
    label: "Projetos Individuais"
    folder: "content/projetos"
    create: true
    editor:
      preview: false
    slug: "{{fields.nome_projeto}}"
    fields:
      - {label: "Nome do projeto", name: "nome_projeto", widget: "string"}
      - {label: "Imagem de capa", name: "imagemCapa", widget: "image"}
      - {label: "Imagem sub-capa", name: "imagemSubCapa", widget: "image"}
      - {label: "Propósito do projeto", name: "textoPurpose", widget: "text"}
      
      # Serviços
      - {label: "Título Serviço 1", name: "t1Services", widget: "string"}
      - {label: "Título Serviço 2", name: "t2Services", widget: "string"}
      - {label: "Título Serviço 3", name: "t3Services", widget: "string"}
      - {label: "Imagem serviço esquerda", name: "imageLeftSer", widget: "image"}
      - {label: "Imagem serviço direita", name: "imageRightSer", widget: "image"}
      - {label: "Imagem serviço inferior", name: "imageBottomSer", widget: "image"}
      
      # Valores
      - {label: "Título Valor 1", name: "t1Values", widget: "string"}
      - {label: "Título Valor 2", name: "t2Values", widget: "string"}
      - {label: "Título Valor 3", name: "t3Values", widget: "string"}
      - {label: "Imagem valor esquerda", name: "imageLeftVal", widget: "image"}
      - {label: "Imagem valor direita", name: "imageRightVal", widget: "image"}
      
      # Equipe
      - {label: "Gerente do projeto", name: "gerente", widget: "string"}
      - label: "Projetistas"
        name: "projetistas"
        widget: "list"
        field: {label: "Nome do Projetista", name: "nome", widget: "string"}
        min: 1
        max: 6
      
      # Links
      - {label: "Texto do botão", name: "bottonText", widget: "string", default: "veja mais no nosso behance!"}
      - {label: "Link do Behance", name: "behanceLink", widget: "string"}
      
      # Projetos Relacionados
      - label: "Projetos Relacionados"
        name: "relacionados"
        widget: "list"
        fields:
          - {label: "Nome do Projeto", name: "nome", widget: "string"}
          - {label: "Imagem", name: "imagem", widget: "image"}
        min: 3
        max: 5

  - name: "contato"
    extension: "json"
    description: "Configurações estáticas da página de contato"
    label: "Contato"
    folder: "content/contato"
    slug: "contatoPage"
    identifier_field: "display_name"
    create: false
    editor:
      preview: false
    fields:
      - {label: "Nome Painel", name: "display_name", widget: "string", hint: "Nome que aparecerá no painel administrativo"}
      - label: "Texto Principal"
        name: "contactText"
        widget: "object"
        fields:
          - {label: "Frase Principal", name: "phrase", widget: "string", default: "empresas que investem em ##design crescem## o dobro das líderes suas indústrias"}
          - {label: "Subfrase", name: "subPhrase", widget: "string", default: "de acordo com o Instituto de Gestão de Design em Boston, EUA"}
      - label: "Formulário"
        name: "contactForm"
        widget: "object"
        fields:
          - {label: "Título do Formulário", name: "headerText", widget: "string", default: "entre em contato com a gente"}
          - {label: "Subtítulo do Formulário", name: "headerSubText", widget: "string", default: "retornamos sua mensagem em até 5 dias úteis."}
          - {label: "Campo Nome", name: "nome", widget: "string", default: "Nome"}
          - {label: "Campo Email", name: "email", widget: "string", default: "E-mail"}
          - {label: "Campo Telefone", name: "telefone", widget: "string", default: "Telefone"}
          - {label: "Campo Tipo de Projeto", name: "tipoProjeto", widget: "string", default: "Qual tipo de projeto?"}
          - {label: "Campo Prazo", name: "prazo", widget: "string", default: "Prazo de Entrega:"}
          - {label: "Campo Onde Conheceu", name: "ondeConheceu", widget: "string", default: "Como conheceu a Faísca?"}
          - {label: "Campo Detalhes", name: "detalhes", widget: "string", default: "Nos conte mais detalhes sobre o seu projeto!"}
          - {label: "Texto Botão Enviar", name: "enviar", widget: "string", default: "Enviar"}

  - name: "footer"
    label: "Footer"
    folder: "content/footer"
    create: true
    extension: "json"
    identifier_field: "altText"
    sortable: true
    editor:
      preview: false
    fields:
      - {label: "Ordem", name: "order", widget: "number", value_type: "int", min: 1}
      - {label: "Nome/Alt Text", name: "altText", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Ícone", name: "icon", widget: "image"}